### PR TITLE
[17.0][MIG] sale_order_analytic_account_mandatory

### PR DESCRIPTION
**Pull request by IriaAlonso**
@dalonsod

### CODE REVIEW

**Review by dalonsod — APPROVED** [review]
:+1:  please first make a rebase, so this PR also contains current 17.0 already merged content.

**Review by dalonsod — CHANGES_REQUESTED** [review]
Locally tested, grouping by analytic account in `search` view doesn't work, could you check?

**Comment by IriaAlonso** [comment]
@dalonsod change done

**Comment by dalonsod** [comment]
> Locally tested, grouping by analytic account in `search` view doesn't work, could you check?

Still doesn't work. Reviewed, v15 original code works, but it's wrong, so it must be fixed here. We need this (add Analytic Account to Group By section):

imagen

**Comment by dalonsod** [comment]
Ahh once made the fix please add yourself as contributor

**Comment by IriaAlonso** [comment]
@dalonsod changes done

**Review by dalonsod — APPROVED** [review]
:+1: I've only removed pending `<?xml>` line, merging...

**Comment by dalonsod** [comment]
@Anxo82 migration finished

**Pull request merged**
