### PR TITLE
[16.0][MIG] sale_order_client_order_ref_mandatory

### PR DESCRIPTION
**Pull request by Anxo82**
Standard migration

### CODE REVIEW

**Comment by Anxo82** [comment]
@dalonsod Review please.
Thanks.

**Comment by dalonsod** [comment]
Regarding to commit history, it's missing README update commit, please check e.g. at 

imagen

README commit: https://github.com/solvosci/slv-sale/commit/ab095932d11c36bdd490a86c23c57040a1cb33ea

This is because README & index files have references to Odoo version.

Anyway, I'll check it ASAP

**Comment by Anxo82** [comment]
@dalonsod Review please.
Thanks.

**Review by dalonsod — CHANGES_REQUESTED** [review]
Functional review, there are two things that must be fixed:
- Order reference field must be required, as addon name suggests. Testing, I could make an order without this field filled. Please check XML view condition.
- Order reference new placement could be updated, because it's now shown very truncated:

  imagen

  In v15 implementation it covers full sheet width:
    
  imagen

**Comment by Anxo82** [comment]
@dalonsod Review please.
Thanks.

**Comment by dalonsod** [comment]
I looks very small now, could you check?

imagen

**Comment by Anxo82** [comment]
@dalonsod I wrote "1,5 em" when it would must be "1.5 em". Fixed
Thanks

**Review by dalonsod — APPROVED** [review]
:+1:

**Pull request merged**
