### PR TITLE
[13.0][ADD] sale_order_line_menu_advanced

### PR DESCRIPTION
**Pull request by dalonsod**
Adds new fields to sale order line menu.

In this first versión first picking and invoice date related to each line are added

### CODE REVIEW

**Comment by dalonsod** [comment]
@ChristianSantamaria @lmiguens-solvos already installed in Test environment, could you check? Thanks!

**Comment by ChristianSantamaria** [comment]
LGTM 👍

**Comment by lmiguens-solvos** [comment]
When I validated a picking in a sales order (VXP22/00248) the following error occurred
File "/home/odoo/odoo-prod/erp-alumisel/src/slv-sale/sale_order_line_menu_advanced/models/sale_order_line.py", line 33, in _compute_picking_first_date
    pickings and pickings.sorted("date_done")[0].date_done
  File "/home/odoo/odoo-prod/erp-alumisel/src/odoo/odoo/models.py", line 5466, in sorted
    return self.browse(item.id for item in sorted(self, key=key, reverse=reverse))
TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime' 

Too when I tried to validate a return picking (VXP22/00252)

**Comment by dalonsod** [comment]
> When I validated a picking in a sales order (VXP22/00248) the following error occurred File "/home/odoo/odoo-prod/erp-alumisel/src/slv-sale/sale_order_line_menu_advanced/models/sale_order_line.py", line 33, in _compute_picking_first_date pickings and pickings.sorted("date_done")[0].date_done File "/home/odoo/odoo-prod/erp-alumisel/src/odoo/odoo/models.py", line 5466, in sorted return self.browse(item.id for item in sorted(self, key=key, reverse=reverse)) TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime'
> 
> Too when I tried to validate a return picking (VXP22/00252)

Didn't reproduce that error. Anyway, the code was wrong when calculating picking first date. Made some fixes, @lmiguens-solvos could you test again?

**Comment by lmiguens-solvos** [comment]
> > When I validated a picking in a sales order (VXP22/00248) the following error occurred File "/home/odoo/odoo-prod/erp-alumisel/src/slv-sale/sale_order_line_menu_advanced/models/sale_order_line.py", line 33, in _compute_picking_first_date pickings and pickings.sorted("date_done")[0].date_done File "/home/odoo/odoo-prod/erp-alumisel/src/odoo/odoo/models.py", line 5466, in sorted return self.browse(item.id for item in sorted(self, key=key, reverse=reverse)) TypeError: '<' not supported between instances of 'bool' and 'datetime.datetime'
> > Too when I tried to validate a return picking (VXP22/00252)
> 
> Didn't reproduce that error. Anyway, the code was wrong when calculating picking first date. Made some fixes, @lmiguens-solvos could you test again?

Now, I can now validate these pickings. It works. LGTM

**Pull request merged**
